#------------------------------------------------------------------------------
# Building the base image with dependencies installed
#------------------------------------------------------------------------------
FROM golang as build

WORKDIR /app

# Download necessary Go modules
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Add all of our code
COPY . /app
ENTRYPOINT ["go", "test", "-v", "./..."]
